import { NextResponse } from "next/server"

// Mock data for projects
const mockProjects = [
  {
    id: "PROJ-001",
    name: "Metro Line Extension Phase 2",
    city: "Mumbai",
    state: "Maharashtra",
    status: "ongoing",
    departments: ["Urban Planning", "Transport", "Finance"],
    projectHead: {
      name: "Dr. Rajesh Kumar",
      title: "Senior Project Manager",
      department: "Urban Planning",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    assignedEmployees: [
      {
        id: "EMP-001",
        name: "Priya Singh",
        designation: "Urban Planner",
        department: "Urban Planning",
        avatar: "/placeholder.svg?height=32&width=32",
      },
      {
        id: "EMP-002",
        name: "Amit Sharma",
        designation: "Transport Engineer",
        department: "Transport",
        avatar: "/placeholder.svg?height=32&width=32",
      },
      {
        id: "EMP-003",
        name: "Neha Gupta",
        designation: "Financial Analyst",
        department: "Finance",
        avatar: "/placeholder.svg?height=32&width=32",
      },
      {
        id: "EMP-004",
        name: "Vikram Mehta",
        designation: "Project Coordinator",
        department: "Urban Planning",
        avatar: "/placeholder.svg?height=32&width=32",
      },
    ],
    budget: "₹2,500 Cr",
    progress: 65,
    startDate: "Jan 2023",
    endDate: "Dec 2024",
    description:
      "Extension of metro line to connect suburban areas with city center, improving public transportation accessibility",
    documents: 45,
    tasks: 120,
    completedTasks: 78,
  },
  {
    id: "PROJ-002",
    name: "Smart Traffic Management System",
    city: "Bangalore",
    state: "Karnataka",
    status: "pending",
    departments: ["Smart City", "Transport", "IT"],
    projectHead: {
      name: "Anita Desai",
      title: "Smart City Director",
      department: "Smart City",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    assignedEmployees: [
      {
        id: "EMP-005",
        name: "Kiran Kumar",
        designation: "Software Engineer",
        department: "IT",
        avatar: "/placeholder.svg?height=32&width=32",
      },
      {
        id: "EMP-006",
        name: "Lakshmi Reddy",
        designation: "Traffic Analyst",
        department: "Transport",
        avatar: "/placeholder.svg?height=32&width=32",
      },
    ],
    budget: "₹150 Cr",
    progress: 25,
    startDate: "Mar 2024",
    endDate: "Mar 2025",
    description: "AI-powered traffic signal optimization and monitoring system to reduce congestion",
    documents: 23,
    tasks: 85,
    completedTasks: 21,
  },
  {
    id: "PROJ-003",
    name: "Water Treatment Plant Upgrade",
    city: "Pune",
    state: "Maharashtra",
    status: "completed",
    departments: ["Water Resources", "Environment", "Public Health"],
    projectHead: {
      name: "Suresh Patil",
      title: "Chief Environmental Engineer",
      department: "Environment",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    assignedEmployees: [
      {
        id: "EMP-007",
        name: "Ravi Agarwal",
        designation: "Water Quality Specialist",
        department: "Water Resources",
        avatar: "/placeholder.svg?height=32&width=32",
      },
      {
        id: "EMP-008",
        name: "Meera Joshi",
        designation: "Public Health Officer",
        department: "Public Health",
        avatar: "/placeholder.svg?height=32&width=32",
      },
    ],
    budget: "₹85 Cr",
    progress: 100,
    startDate: "Jun 2022",
    endDate: "Completed",
    description: "Modernization of water treatment facilities to serve 2M residents with improved water quality",
    documents: 67,
    tasks: 95,
    completedTasks: 95,
  },
  {
    id: "PROJ-004",
    name: "Digital Governance Portal",
    city: "New Delhi",
    state: "Delhi",
    status: "ongoing",
    departments: ["IT", "Administration", "Citizen Services"],
    projectHead: {
      name: "Rohit Verma",
      title: "Chief Technology Officer",
      department: "IT",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    assignedEmployees: [
      {
        id: "EMP-009",
        name: "Sanjay Kumar",
        designation: "Full Stack Developer",
        department: "IT",
        avatar: "/placeholder.svg?height=32&width=32",
      },
      {
        id: "EMP-010",
        name: "Pooja Sharma",
        designation: "UX Designer",
        department: "IT",
        avatar: "/placeholder.svg?height=32&width=32",
      },
      {
        id: "EMP-011",
        name: "Rahul Singh",
        designation: "Business Analyst",
        department: "Administration",
        avatar: "/placeholder.svg?height=32&width=32",
      },
    ],
    budget: "₹45 Cr",
    progress: 80,
    startDate: "Sep 2023",
    endDate: "Aug 2024",
    description: "Unified platform for all citizen services and government processes with digital transformation",
    documents: 34,
    tasks: 150,
    completedTasks: 120,
  },
  {
    id: "PROJ-005",
    name: "Solar Park Development",
    city: "Jaipur",
    state: "Rajasthan",
    status: "pending",
    departments: ["Energy", "Environment", "Land Development"],
    projectHead: {
      name: "Dr. Kavita Agarwal",
      title: "Renewable Energy Director",
      department: "Energy",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    assignedEmployees: [
      {
        id: "EMP-012",
        name: "Manoj Gupta",
        designation: "Solar Engineer",
        department: "Energy",
        avatar: "/placeholder.svg?height=32&width=32",
      },
      {
        id: "EMP-013",
        name: "Sunita Sharma",
        designation: "Environmental Consultant",
        department: "Environment",
        avatar: "/placeholder.svg?height=32&width=32",
      },
    ],
    budget: "₹300 Cr",
    progress: 15,
    startDate: "Apr 2024",
    endDate: "Jun 2025",
    description: "500MW solar power generation facility for sustainable energy and carbon footprint reduction",
    documents: 18,
    tasks: 200,
    completedTasks: 30,
  },
  {
    id: "PROJ-006",
    name: "Waste Management Automation",
    city: "Hyderabad",
    state: "Telangana",
    status: "ongoing",
    departments: ["Sanitation", "Environment", "Smart City"],
    projectHead: {
      name: "Venkat Reddy",
      title: "Sanitation Director",
      department: "Sanitation",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    assignedEmployees: [
      {
        id: "EMP-014",
        name: "Arjun Rao",
        designation: "IoT Specialist",
        department: "Smart City",
        avatar: "/placeholder.svg?height=32&width=32",
      },
      {
        id: "EMP-015",
        name: "Divya Nair",
        designation: "Operations Manager",
        department: "Sanitation",
        avatar: "/placeholder.svg?height=32&width=32",
      },
      {
        id: "EMP-016",
        name: "Rajesh Babu",
        designation: "Environmental Monitor",
        department: "Environment",
        avatar: "/placeholder.svg?height=32&width=32",
      },
    ],
    budget: "₹120 Cr",
    progress: 45,
    startDate: "Feb 2024",
    endDate: "Nov 2024",
    description: "IoT-enabled waste collection and processing system with real-time monitoring and optimization",
    documents: 29,
    tasks: 110,
    completedTasks: 50,
  },
]

export async function GET() {
  try {
    // Simulate API delay
    await new Promise((resolve) => setTimeout(resolve, 500))

    return NextResponse.json({
      success: true,
      projects: mockProjects,
      total: mockProjects.length,
    })
  } catch (error) {
    return NextResponse.json({ success: false, error: "Failed to fetch projects" }, { status: 500 })
  }
}
